const PDFDocument = require('pdfkit');
const { createWriteStream } = require('fs');
const path = require('path');

const generateElectionResultsPDF = async (election, results) => {
  return new Promise((resolve, reject) => {
    const fileName = `election-results-${election.id}-${Date.now()}.pdf`;
    const filePath = path.join(__dirname, '../reports', fileName);

    const doc = new PDFDocument();
    const stream = createWriteStream(filePath);

    doc.on('error', reject);
    stream.on('error', reject);

    doc.pipe(stream);

    // Title
    doc.fontSize(25).font('Helvetica-Bold').text('Election Results Report', 100, 100);
    doc.fontSize(12).font('Helvetica').text(`Election: ${election.title}`, 100, 140);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 100, 160);

    // Election Details
    doc.fontSize(14).font('Helvetica-Bold').text('Election Details', 100, 200);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Start Date: ${new Date(election.start_date).toLocaleString()}`, 100, 225);
    doc.text(`End Date: ${new Date(election.end_date).toLocaleString()}`, 100, 245);
    doc.text(`Status: ${election.status.toUpperCase()}`, 100, 265);
    doc.text(`Description: ${election.description || 'N/A'}`, 100, 285);

    // Results Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Results Summary', 100, 330);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Votes Cast: ${results.total_votes}`, 100, 355);
    doc.text(`Total Registered Voters: ${results.total_voters}`, 100, 375);
    doc.text(`Voter Turnout: ${((results.total_votes / results.total_voters) * 100).toFixed(2)}%`, 100, 395);

    // Candidate Results
    doc.fontSize(14).font('Helvetica-Bold').text('Candidate-wise Results', 100, 440);
    
    let yPosition = 470;
    doc.fontSize(11).font('Helvetica-Bold');
    doc.text('Candidate Name', 100, yPosition);
    doc.text('Votes', 300, yPosition);
    doc.text('Percentage', 380, yPosition);
    
    yPosition += 20;
    doc.moveTo(100, yPosition).lineTo(480, yPosition).stroke();
    yPosition += 10;

    doc.font('Helvetica');
    results.candidates.forEach((candidate, index) => {
      const percentage = results.total_votes > 0 
        ? ((candidate.vote_count / results.total_votes) * 100).toFixed(2)
        : '0.00';

      doc.text(candidate.name, 100, yPosition);
      doc.text(candidate.vote_count.toString(), 300, yPosition);
      doc.text(`${percentage}%`, 380, yPosition);

      yPosition += 25;

      if (yPosition > 700) {
        doc.addPage();
        yPosition = 50;
      }
    });

    // Winner
    if (results.candidates.length > 0) {
      const winner = results.candidates.reduce((max, candidate) => 
        candidate.vote_count > max.vote_count ? candidate : max
      );

      yPosition += 20;
      doc.fontSize(14).font('Helvetica-Bold').text('Election Winner', 100, yPosition);
      yPosition += 30;
      doc.fontSize(12).font('Helvetica').text(`Winner: ${winner.name}`, 100, yPosition);
      doc.text(`Votes Received: ${winner.vote_count}`, 100, yPosition + 20);
      doc.text(`Vote Percentage: ${((winner.vote_count / results.total_votes) * 100).toFixed(2)}%`, 100, yPosition + 40);
    }

    // Footer
    doc.fontSize(10).font('Helvetica').text('This is an official report generated by Smart E-Voting System.', 100, 750, { align: 'center' });

    doc.end();

    stream.on('finish', () => {
      resolve(filePath);
    });
  });
};

module.exports = {
  generateElectionResultsPDF
};
